### ISSUE TITLE
Achtergrond

### ISSUE THREAD

**Issue by Hadil66** [DamianR2004/your-tribe-for-life-profile-card#10]
Het is misschien beter om een andere achtergrond te gebruiken voor de dark-mode. Die je nu hebt, is niet erg scherp; het zou misschien beter zijn om er een te vinden met een hogere kwaliteit.

**Comment by DamianR2004** [comment]
De achtergrond hoort bij het design, vandaar dat deze onscherp is. Toch bedankt voor de tip!
